name: JRPCExamplePlugin
version: '${version}'
main: net.sxlver.jrpc.exampleplugin.JRPCExamplePlugin
api-version: 1.13

depend:
  - JRPCBukkit

commands:
  locateplayer:
    description: locates a player across the network
    aliases:
      - locate
      - findplayer
  playerlist:
    description: lists online players on the target server
    aliases:
      - online
  broadcast:
    description: broadcasts a message across the network to players with the specified permission
  listservers:
    description: lists servers in the network
  benchmark:
    description: runs a benchmark by sending x amount of requests to every client in the network


