name: JRPCExamplePlugin
version: '${version}'
main: net.sxlver.jrpc.exampleplugin.JRPCExamplePlugin
api-version: 1.13

depend:
  - JRPCBukkit

commands:
  locateplayer:
    description: locates a player across the network
    aliases:
      - locate
      - findplayer
  playerlist:
    description: lists online players on the target server
    aliases:
      - online


